version: '3'
services:
  add_lat_long_ra_events:
    container_name: "add_lat_long_ra_events"
    build: .
    command: "npm run prod"
    environment:
      - NODE_ENV=production
    image: f4zphp27xi2s27yn/my_repo_topor:ra_events_lat_long_venue_add
networks:
  default:
    name: ra_events_grabber_network
    external: true
