version: '3'
services:
  add_lat_long_ra_events:
    container_name: "add_lat_long_ra_events"
    build: .
    command: "npm run prod"
    environment:
      - NODE_ENV=production
networks:
  default:
    name: ra_events_grabber_network
    external: true
